[target.thumbv7m-none-eabi]
runner = "probe-rs run --chip STM32F103C8Tx"
#linker = "clang"
rustflags=[
	"-C","link-arg=-Tlink.x",
	#"-C", "debuginfo=0",
	#"-C", "strip=symbols",
	#"-C", "link-arg=-fuse-ld=mold",
]

[build]
target = "thumbv7m-none-eabi"
